# Generated by Django 3.2.12 on 2022-04-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0002_faturamento_conta_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
