# Generated by Django 3.2.12 on 2022-05-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0005_faturamento_energia_da_concessionaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cliente', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='faturamento',
            name='usuario',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='cpf_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geracao.cliente'),
        ),
    ]
