# Generated by Django 3.2.12 on 2022-05-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0006_auto_20220501_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='instalacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='consumoSimulado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='consumo_mes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='custo_disponibilidade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='desconto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='energia_da_concessionaria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='franquia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='iluminacaoPublica',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='injetada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='tarifa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='tarifaInjetada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='totalPagar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='totalSimulado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='valorConsumoSimulado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturamento',
            name='valorInjetado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
