# Generated by Django 3.2.12 on 2022-05-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0008_faturamento_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='referencia',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
