# Generated by Django 3.2.12 on 2022-05-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0011_auto_20220505_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='referencia',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
