# Generated by Django 3.2.12 on 2022-05-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0012_alter_faturamento_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='custo_disponibilidade_simulado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
