# Generated by Django 3.2.12 on 2022-05-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0013_faturamento_custo_disponibilidade_simulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
