# Generated by Django 3.2.12 on 2022-05-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0015_auto_20220510_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
