# Generated by Django 3.2.12 on 2022-05-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0016_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='charles.wilis@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='percentual',
            field=models.FloatField(default=20),
        ),
    ]
