# Generated by Django 3.2.12 on 2022-05-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0017_auto_20220515_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
