# Generated by Django 3.2.12 on 2022-05-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0021_faturamento_novo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturamento',
            name='novo',
        ),
    ]
