# Generated by Django 3.2.12 on 2022-05-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0023_faturamento_distribuidora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamento',
            name='distribuidora',
            field=models.CharField(max_length=10),
        ),
    ]
