# Generated by Django 3.2.12 on 2022-05-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0024_alter_faturamento_distribuidora'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='acerto',
            field=models.FloatField(default=0),
        ),
    ]
