# Generated by Django 3.2.12 on 2023-02-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0025_faturamento_acerto'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='conta_txt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
