# Generated by Django 3.2.12 on 2024-04-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0026_faturamento_conta_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='chave_pix_cobranca',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
