# Generated by Django 3.2.12 on 2022-04-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumoSimulado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custo_disponibilidade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consumo_mes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('franquiaCemig', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iluminacaoPublica', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('injetada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('porte', models.CharField(blank=True, max_length=15, null=True)),
                ('tarifaCemig', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tarifaInjetada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalSimulado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalPagar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorConsumoSimulado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valorInjetado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
