# Generated by Django 3.2.12 on 2022-04-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0003_faturamento_desconto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faturamento',
            old_name='franquiaCemig',
            new_name='franquia',
        ),
        migrations.RenameField(
            model_name='faturamento',
            old_name='tarifaCemig',
            new_name='tarifa',
        ),
    ]
