# Generated by Django 3.2.12 on 2022-05-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0009_alter_faturamento_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='vencimento',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
