# Generated by Django 3.2.12 on 2022-05-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0010_faturamento_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='economia_percentual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='economia_valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
