# Generated by Django 3.2.12 on 2022-05-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0018_auto_20220515_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='percentual',
            new_name='desconto',
        ),
    ]
