# Generated by Django 3.2.12 on 2022-05-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geracao', '0019_rename_percentual_cliente_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='nome',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
